name: Docker

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  cancel-in-progress: true
  group: docker-${{ github.event.pull_request.number || github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t libd4 .
      - run: docker run libd4
