name: Install

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  cancel-in-progress: true
  group: install-${{ github.event.pull_request.number || github.sha }}

jobs:
  install:
    runs-on: ${{ matrix.config.os }}
    permissions:
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-13
          - os: macos-14
            install-prefix: sudo
          - os: macos-15
            install-prefix: sudo
          - os: ubuntu-22.04
            install-prefix: sudo
          - os: ubuntu-24.04
            install-prefix: sudo
          - os: windows-2019
          - os: windows-2022
          - os: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: ilammy/setup-nasm@v1
      - uses: actions/cache@v4
        with:
          path: |
            build/openssl
            build/openssl-prefix
            build/openssl-src
          key: cmake-openssl-${{ matrix.config.os }}-${{ hashFiles('cmake/DownloadOpenSSL.cmake') }}
      - run: cmake . -B ./build -D LIBD4_BUILD_EXAMPLES=ON -D LIBD4_BUILD_TESTS=ON
      - run: cmake --build build --config Debug
      - run: ${{ matrix.config.install-prefix }} cmake --install build
