name: Test Docker

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  cancel-in-progress: true
  group: test-docker-${{ github.event.pull_request.number || github.sha }}

jobs:
  test-docker:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-latest
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'macOS'
        run: brew install docker && colima start
      - run: docker build -t libd4 .
      - run: docker run libd4
