name: Test Release

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  cancel-in-progress: true
  group: test-release-${{ github.event.pull_request.number || github.sha }}

jobs:
  test-release:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-12
          - os: macos-13
          - os: macos-14
            install-prefix: sudo
          - os: ubuntu-20.04
            install-prefix: sudo
          - os: ubuntu-22.04
            install-prefix: sudo
          - os: windows-2019
          - os: windows-2022
    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - if: runner.os == 'Windows'
        uses: ilammy/setup-nasm@v1
      - uses: actions/cache@v4
        with:
          path: |
            build/openssl
            build/openssl-prefix
            build/openssl-src
          key: cmake-openssl-${{ matrix.config.os }}-${{ hashFiles('cmake/DownloadOpenSSL.cmake') }}
      - if: runner.os == 'Windows'
        run: New-Item -ItemType Directory -Force -Path build
      - if: runner.os != 'Windows'
        run: mkdir -p build
      - run: cmake . -B ./build
      - run: cmake --build build --config Release
      - run: ${{ matrix.config['install-prefix'] }} cmake --install build
