name: Test Coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  cancel-in-progress: true
  group: test-coverage-${{ github.event.pull_request.number || github.sha }}

jobs:
  test-coverage:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: thelang-io/setup-the@v1
      - uses: actions/cache@v4
        with:
          path: |
            coverage/openssl
            coverage/openssl-prefix
            coverage/openssl-src
          key: coverage-cmake-openssl-macos-${{ hashFiles('cmake/DownloadOpenSSL.cmake') }}
      - run: brew install lcov
      - run: mkdir -p coverage
      - run: cmake . -B ./coverage -D LIBD4_BUILD_TESTS=ON -D LIBD4_COVERAGE=ON
      - run: cmake --build coverage --config Debug
      - run: ctest --output-on-failure --test-dir coverage
      - run: lcov --branch-coverage --capture -d coverage -o coverage/test.info --exclude 'test/*'
      - run: genhtml -o coverage/html coverage/test.info
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: coverage/html
      - run: the install
      - run: the script check-total-coverage
