name: Unit Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  cancel-in-progress: true
  group: unit-tests-${{ github.event.pull_request.number || github.sha }}

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    permissions:
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-13
          - os: macos-14
          - os: macos-15
          - os: ubuntu-22.04
          - os: ubuntu-24.04
          - os: windows-2019
          - os: windows-2022
          - os: windows-2025
    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - if: runner.os == 'Windows'
        uses: ilammy/setup-nasm@v1
      - uses: actions/cache@v4
        with:
          path: |
            build/openssl
            build/openssl-prefix
            build/openssl-src
          key: cmake-openssl-${{ matrix.config.os }}-${{ hashFiles('cmake/DownloadOpenSSL.cmake') }}
      - if: runner.os == 'Windows'
        run: New-Item -ItemType Directory -Force -Path build
      - if: runner.os != 'Windows'
        run: mkdir -p build
      - run: cmake . -B ./build -D LIBD4_BUILD_EXAMPLES=ON -D LIBD4_BUILD_TESTS=ON -D LIBD4_SANITIZER=ON
      - run: cmake --build build --config Debug
      - run: ctest --output-on-failure --test-dir build
